In [1]:
import os
import torch

In [2]:
with open('log_batches_no_preload.txt', 'r') as f:
    lines = f.read()

In [3]:
res = list(map(lambda s: (int(s[0]), list(map(int, s[3:].split('\n')))), lines.split('Worker ')[1:]))

# 83 epochs

In [4]:
batches = torch.Tensor(list(map(lambda t: t[1], res))).type(torch.int32)
batches, batches.shape

(tensor([[33081, 28834, 30417,  ..., 28734, 17291, 10679],
         [ 9693,   528, 23248,  ...,  7474, 11558,  9302],
         [10123, 26332,  1855,  ..., 28751, 26932, 11089],
         ...,
         [34143,  4398,   131,  ..., 25809,  7716,  7097],
         [ 6307, 14510,  1884,  ..., 22205, 16429, 35851],
         [ 7170, 15826, 11466,  ..., 36310,  4562,  7158]], dtype=torch.int32),
 torch.Size([63696, 48]))

In [5]:
epoch_batches = batches[:751*83].reshape((83, -1, 48))

In [6]:
epoch_batches, epoch_batches.shape

(tensor([[[33081, 28834, 30417,  ..., 28734, 17291, 10679],
          [ 9693,   528, 23248,  ...,  7474, 11558,  9302],
          [10123, 26332,  1855,  ..., 28751, 26932, 11089],
          ...,
          [ 9693,   528, 23248,  ...,  7474, 11558,  9302],
          [10123, 26332,  1855,  ..., 28751, 26932, 11089],
          [11941,  9533, 26678,  ..., 19842, 11038, 32111]],
 
         [[29790, 12451, 16563,  ..., 16028,  1576, 17098],
          [30341, 18058, 36810,  ...,  9219,  4709, 16413],
          [18409,   747, 33701,  ..., 26783, 25193, 18717],
          ...,
          [36188, 29296, 30661,  ..., 34284,  2843, 20491],
          [ 3985, 26543, 16500,  ...,  8998, 37089, 17531],
          [37123, 16808, 17098,  ..., 37151, 20808, 36748]],
 
         [[14114, 33433,  3409,  ...,  4930,  3082, 11879],
          [34315, 28309, 10703,  ...,  7115, 17650, 18135],
          [ 1163, 37698,  3521,  ..., 17663, 11491, 13411],
          ...,
          [33473, 33704,  6763,  ..., 23102, 2557

In [7]:
torch.save(epoch_batches, 'saved_epochs_batches.pt')

In [ ]:
import torch 
# import yaml
import os
import os.path as osp
from tqdm import tqdm
import sys

epochs_batches = []
for epoch in tqdm(range(130), position=0):
    epoch_folder = osp.join('batch_logs', f'epoch_{epoch:03d}')
    batches = torch.stack([torch.load(file_path) for file_path in tqdm(list(map(lambda s: osp.join(epoch_folder, s), sorted(os.listdir(epoch_folder), key=lambda s: int(s.split('_')[1])))), position=1, leave=False)])
    epochs_batches.append(batches)

storage_space = sum(map(lambda batches: sys.getsizeof(batches.storage()), epochs_batches))
print(storage_space / 1024 / 1024, 'MB')

100%|██████████| 130/130 [07:12<00:00,  3.33s/it]

17.680023193359375 MB



/tmp/ipykernel_209099/1066041949.py:14: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage_space = sum(list(map(lambda batches: sys.getsizeof(batches.storage()), epochs_batches)))


In [8]:
storage_space = sum(map(lambda batches: sys.getsizeof(batches.storage()), epochs_batches))
print(storage_space / 1024 / 1024, 'MB')

17.680023193359375 MB


In [ ]:
sys.getsizeof(epochs_batches[0].storage()) / 1024 / 1024

0.1364593505859375

In [16]:
import pickle

In [18]:
with open('saved_epochs_batches.pkl', 'wb') as f:
    pickle.dump(epochs_batches, f)

In [ ]:
import pickle
with open('saved_epochs_batches.pkl', 'rb') as f:
    saved_epochs_batches = pickle.load(f)

In [20]:
saved_epochs_batches

[tensor([[33081, 28834, 30417,  ..., 28734, 17291, 10679],
         [ 9693,   528, 23248,  ...,  7474, 11558,  9302],
         [10123, 26332,  1855,  ..., 28751, 26932, 11089],
         ...,
         [17756, 19880, 34300,  ..., 22738,  2123, 31066],
         [13684, 31699,  1111,  ..., 23023, 28437,     1],
         [ 9671, 12751, 18104,  ..., 34412, 10217, 37613]], dtype=torch.int32),
 tensor([[24648,  1342, 10767,  ..., 31656, 29871, 10813],
         [35627, 10244,  4323,  ..., 36118, 37505, 24996],
         [13935,  1638, 28324,  ..., 18918,  2495, 15094],
         ...,
         [33926, 15024,  7445,  ..., 23041,  4808, 14060],
         [35769,  1838,  1300,  ..., 17681,  5763,  3063],
         [29555,   307, 14493,  ..., 19988, 31976, 29189]], dtype=torch.int32),
 tensor([[22445,  5788, 11565,  ..., 31104,   570, 15112],
         [34995,  9793, 27577,  ..., 33070,  3018, 23573],
         [24418, 20542, 21544,  ..., 28828, 23788, 14650],
         ...,
         [15197, 16519, 15472, 